name: 
channels:
  - defaults
dependencies:
  - python==3.8.10
  - matplotlib
  - tqdm
  - jupyter
  - pip
  - pip:
    - torch==1.13.1
    - torchtext==0.14.1
    - notebook
    - numpy
    - spacy==3.7.2
